name: ci

on: pull_request

permissions:
  contents: read

jobs:
  plugin:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-ci.yml@26d71413024508c19579a7df94d93488c4fe3bbf
    secrets: inherit
